### ISSUE TITLE
Help using your localization files!

### ISSUE THREAD

**Issue by Byron657** [brlima94/acat#2]
Hello, a close friend of mine is slowly dying for Multiple sclerosis (MS), she can only use her eyes almost. We wanted to use ACAT to let her communicate with us but the word prediction in Italian is not officially released. I found your repository but it says it needs (the last release) the v0.98 version, which is impossibile to find because 1org removed the exe from the github page, can you please help me? We want to "hear" her one last time and make her happy...Thanks.

**Comment by nanomo** [comment]
Hi @Byron657, there is a manual to create new language translation files, check page 38:
https://01.org/sites/default/files/documentation/acat_developers_guide_3.pdf

Do you have any skill on programming? let me know if you need some help, i dont know nothing of italian but have some skills coding and least the text, the text to speech engine will need other setup.

**Comment by Byron657** [comment]
Hello @nanomo, I already saw that and it's talking about the translation of the UI, I can do that immediatly, but it says I also need to search for a word prediction database, I don't know where to take it or make it. Unfortunately I have not programming skills, I use this account just to comment I'm sorry. I tried the italian word prediction db included in @brlima94 release but it's very poor and missing basic words (not mentioning it works only with an old release of ACAT which is impossible to find, I should compile myself and I'm not able to do it, I was able to test the db because I copied everything in the last release of ACAT, but because it contains also modified exe files obviously it broke almost everything but I was able to test the italian prediction db using the keyboard and it's missing a lot of words and it does strange connections to the next words), do you have any tips?

**Comment by brlima94** [comment]
Hi @Byron657 , sorry for my late response. I used the italian database shipped with Presage by default. Could you provide some sample text so I can build a better database for you?
I'm also sending you a spreadsheet ([ACAT UI Translation Spreadsheet v3.xlsx](https://github.com/brlima94/acat-localization/files/923809/ACAT.UI.Translation.Spreadsheet.v3.xlsx)), if you can translate that and send back to me I'll create a language pack you can use in latest version of ACAT. Please fill in sheet "Italian", column "Translation - (D)".
If you need any more help, please let me know.

**Comment by fdavison** [comment]
Hi @brlima94,

I hope you are still willing to create an Italian language pack:
I have attached an Italian translation for your spreadsheet: [ACAT.UI.Translation.Spreadsheet.v3.xlsx](https://github.com/brlima94/acat-localization/files/1524987/ACAT.UI.Translation.Spreadsheet.v3.xlsx)

For the prediction database, these two books should be good:

[https://www.gutenberg.org/ebooks/44763](https://www.gutenberg.org/ebooks/44763)
[https://www.gutenberg.org/ebooks/30369](https://www.gutenberg.org/ebooks/30369)

I have tried building ACAT myself in Visual Studio 2012 and 2017 without any luck.

**Comment by brlima94** [comment]
Hi @fdavison, how're you doing?
I'm sure interested in also creating an Italian language pack.
I gave a quick look at the attached spreadsheet and it seems to be missing two sentences:
* **Max /   Snap -->** is that icon between Minimize and Close buttons, that it's used to maximize and/or reduce the size of the focused window
* **Parent Dir -->** in Windows Explorer, when clicked, navigates to the "parent" folder (e.g.: from "C:\ACAT\" to "C:\")

Could you please add these sentences and send me an updated spreadsheet?
PS: I didn't double checked all sentences, just filtered for empty values in Translation column.

**Comment by fdavison** [comment]
Thank you!  I have attached the updated spreadsheet:  
[ACAT.UI.Translation.Spreadsheet.v3.xlsx](https://github.com/brlima94/acat-localization/files/1528116/ACAT.UI.Translation.Spreadsheet.v3.xlsx)

**Comment by fdavison** [comment]
@brlima94 please let me know if you need anything else

**Comment by brlima94** [comment]
Hi @fdavison, sorry for the late. I made a draft based on the files you sent.
Can you please check if this works for you? [ACATItalianLanguagePack.zip](https://github.com/brlima94/acat-localization/files/1671266/ACATItalianLanguagePack.zip)

**Comment by fdavison** [comment]
@brlima94 it appears to work!  Bellissimo!  I will forward it to my Italian friend who will be using it and give it a more complete test.  Thank you so much.
